# Generated by Django 4.2.8 on 2024-09-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Algae",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("phylum", models.CharField(blank=True, max_length=100, null=True)),
                ("class_name", models.CharField(blank=True, max_length=100, null=True)),
                ("order", models.CharField(blank=True, max_length=100, null=True)),
                ("family", models.CharField(blank=True, max_length=100, null=True)),
                ("environment", models.TextField(blank=True, null=True)),
                (
                    "toxicity_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Toxic", "Toxic"),
                            ("Harmful", "Harmful"),
                            ("Both", "Toxic/Harmful"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
