# Generated by Django 4.2.8 on 2024-09-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="algae",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="algae",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="algae_images/"),
        ),
    ]
