# Generated by Django 4.2.8 on 2024-09-19 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0002_algae_description_algae_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chemical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("classification", models.CharField(max_length=200)),
                ("source", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "np_classification",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("casNumber", models.CharField(max_length=200, verbose_name="CAS")),
                ("isnp", models.BooleanField(verbose_name="是否为天然产物")),
                ("smiles", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=200)),
                ("publishing_time", models.DateField()),
                ("doi", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("initialDensity", models.CharField(max_length=200)),
                ("time", models.CharField(max_length=200)),
                ("ec50", models.FloatField()),
                ("cultivationSystem", models.CharField(max_length=200)),
                ("Irradiance", models.CharField(max_length=200)),
                ("temperature", models.CharField(max_length=200)),
                ("cultureMedium", models.CharField(max_length=200)),
                ("mechenism", models.TextField(blank=True, null=True)),
                (
                    "algae",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="algaecide.algae",
                    ),
                ),
                (
                    "chemical",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="algaecide.chemical",
                    ),
                ),
                (
                    "reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="algaecide.reference",
                    ),
                ),
            ],
        ),
    ]
