# Generated by Django 4.2.8 on 2024-09-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0003_chemical_reference_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="chemical",
            name="origin",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Plant", "Plant"),
                    ("Microorganism", "Microorganism"),
                    ("Chemical", "Chemical"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
