# Generated by Django 4.2.8 on 2024-09-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0004_chemical_origin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chemical",
            name="casNumber",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="CAS"
            ),
        ),
        migrations.AlterField(
            model_name="chemical",
            name="classification",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="chemical",
            name="smiles",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="Irradiance",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="cultivationSystem",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="cultureMedium",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="ec50",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="initialDensity",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="temperature",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="time",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
