# Generated by Django 4.2.8 on 2024-09-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0005_alter_chemical_casnumber_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reference",
            name="publishing_time",
        ),
        migrations.AddField(
            model_name="reference",
            name="publication_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="reference",
            name="publication_year",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reference",
            name="url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="reference",
            name="author",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="reference",
            name="doi",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="reference",
            name="title",
            field=models.TextField(),
        ),
    ]
