# Generated by Django 4.2.8 on 2024-09-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0007_chemical_pubchem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record",
            name="ec50",
        ),
        migrations.AddField(
            model_name="record",
            name="effect",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="record",
            name="measurement",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="record",
            name="unit",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="time",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
