# Generated by Django 4.2.8 on 2024-09-24 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "algaecide",
            "0008_remove_record_ec50_record_effect_record_measurement_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.CharField(max_length=255)),
                ("measurement_type", models.CharField(max_length=255)),
                ("effect", models.DecimalField(decimal_places=4, max_digits=10)),
                ("unit", models.CharField(max_length=50)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="algaecide.record",
                    ),
                ),
            ],
        ),
    ]
