# Generated by Django 4.2.8 on 2024-09-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0009_measurement"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="other_measurements",
            field=models.TextField(blank=True, null=True),
        ),
    ]
