# Generated by Django 4.2.8 on 2024-09-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0010_record_other_measurements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chemical",
            name="smiles",
            field=models.TextField(blank=True, null=True),
        ),
    ]
