# Generated by Django 4.2.8 on 2024-09-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0011_alter_chemical_smiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="Response_endpoint",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
