# Generated by Django 4.2.8 on 2024-09-25 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0012_record_response_endpoint"),
    ]

    operations = [
        migrations.RenameField(
            model_name="record",
            old_name="Response_endpoint",
            new_name="response_endpoint",
        ),
    ]
