# Generated by Django 4.2.8 on 2024-09-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0013_rename_response_endpoint_record_response_endpoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="is_checked",
            field=models.BooleanField(default=False),
        ),
    ]
