# Generated by Django 4.2.8 on 2024-09-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0014_reference_is_checked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="effect",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
