# Generated by Django 4.2.8 on 2024-09-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0015_alter_record_effect"),
    ]

    operations = [
        migrations.AddField(
            model_name="algae",
            name="strain",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
