# Generated by Django 4.2.8 on 2024-09-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0016_algae_strain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="algae",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
