# Generated by Django 4.2.8 on 2024-10-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0017_alter_algae_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="algae",
            name="toxicity_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
