# Generated by Django 4.2.8 on 2024-11-05 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0018_alter_algae_toxicity_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlgaeSpecies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("phylum", models.CharField(blank=True, max_length=100, null=True)),
                ("class_name", models.CharField(blank=True, max_length=100, null=True)),
                ("order", models.CharField(blank=True, max_length=100, null=True)),
                ("family", models.CharField(blank=True, max_length=100, null=True)),
                ("environment", models.TextField(blank=True, null=True)),
                (
                    "toxicity_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="algae_images/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AlgaeStrain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strain", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strains",
                        to="algaecide.algaespecies",
                    ),
                ),
            ],
        ),
    ]
