# Generated by Django 4.2.8 on 2024-11-05 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0019_algaespecies_algaestrain_alter_record_algae"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="algae_strain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="algaecide.algaestrain",
            ),
        ),
    ]
