# Generated by Django 4.2.8 on 2024-11-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0020_record_algae_strain"),
    ]

    operations = [
        migrations.RenameField(
            model_name="algaespecies",
            old_name="toxicity_type",
            new_name="risk",
        ),
        migrations.AddField(
            model_name="algaespecies",
            name="description_source",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="algaespecies",
            name="image_source",
            field=models.URLField(blank=True, null=True),
        ),
    ]
