# Generated by Django 4.2.8 on 2024-11-06 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0021_rename_toxicity_type_algaespecies_risk_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="record",
            old_name="mechenism",
            new_name="mechanism",
        ),
    ]
