# Generated by Django 4.2.8 on 2024-11-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0022_rename_mechenism_record_mechanism"),
    ]

    operations = [
        migrations.AddField(
            model_name="chemical",
            name="pubchem_cid",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
