# Generated by Django 4.2.8 on 2024-11-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0023_chemical_pubchem_cid"),
    ]

    operations = [
        migrations.AddField(
            model_name="chemical",
            name="pubchem_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
