# Generated by Django 4.2.8 on 2024-11-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0024_chemical_pubchem_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="chemical",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="chemical_images/"
            ),
        ),
    ]
