# Generated by Django 4.2.8 on 2024-11-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0025_chemical_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="chemical",
            name="InChI",
            field=models.TextField(blank=True, null=True),
        ),
    ]
