# Generated by Django 4.2.8 on 2024-11-08 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0026_chemical_inchi"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="algaespecies",
            options={"verbose_name_plural": "Algae species"},
        ),
        migrations.AlterField(
            model_name="record",
            name="algae",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="algaecide.algae",
            ),
        ),
    ]
