# Generated by Django 4.2.8 on 2024-11-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0027_alter_algaespecies_options_alter_record_algae"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="measurement",
            name="record",
        ),
        migrations.AddField(
            model_name="record",
            name="measurements",
            field=models.ManyToManyField(
                related_name="records", to="algaecide.measurement"
            ),
        ),
    ]
