# Generated by Django 4.2.8 on 2024-11-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0028_remove_measurement_record_record_measurements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="measurements",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="records",
                to="algaecide.measurement",
            ),
        ),
    ]
