# Generated by Django 4.2.8 on 2024-11-08 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0029_alter_record_measurements"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record",
            name="measurements",
        ),
    ]
