# Generated by Django 4.2.8 on 2024-11-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0030_remove_record_measurements"),
    ]

    operations = [
        migrations.AddField(
            model_name="algae",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chemical",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="record",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
