# Generated by Django 4.2.8 on 2024-11-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0031_algae_note_chemical_note_record_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="algaespecies",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
