# Generated by Django 4.2.8 on 2024-11-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0032_algaespecies_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chemical",
            name="isnp",
            field=models.BooleanField(),
        ),
    ]
