# Generated by Django 4.2.8 on 2024-11-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algaecide', '0033_alter_chemical_isnp'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
