# Generated by Django 4.2.8 on 2024-11-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algaecide', '0034_reference_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='algaespecies',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
