# Generated by Django 4.2.8 on 2024-11-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algaecide', '0035_algaespecies_is_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algaespecies',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
