# Generated by Django 4.2.8 on 2024-11-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algaecide', '0036_alter_algaespecies_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algaespecies',
            name='description_source',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
