# Generated by Django 4.2.8 on 2024-11-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algaecide', '0037_alter_algaespecies_description_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='algaespecies',
            name='empire',
            field=models.CharField(blank=True, default='Eukaryota', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='algaespecies',
            name='kingdom',
            field=models.CharField(blank=True, default='Chromista', max_length=100, null=True),
        ),
    ]
