# Generated by Django 4.2.8 on 2024-12-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algaecide', '0039_algaespecies_algaebaselink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Measurement',
        ),
        migrations.AlterField(
            model_name='chemical',
            name='origin',
            field=models.CharField(blank=True, choices=[('Animal', 'Animal'), ('Plant', 'Plant'), ('Microorganism', 'Microorganism'), ('Chemical', 'Chemical')], max_length=20, null=True),
        ),
    ]
