# Generated by Django 4.2.8 on 2024-12-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0041_chemical_form_reference_toxicity_check_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="is_derivative",
            field=models.BooleanField(default=False),
        ),
    ]
