# Generated by Django 4.2.8 on 2024-12-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0042_reference_is_derivative"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="unit",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
