# Generated by Django 4.2.8 on 2024-12-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0043_alter_record_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chemical",
            name="origin",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Animal", "Animal"),
                    ("Plant", "Plant"),
                    ("Microorganism", "Microorganism"),
                    ("Chemical", "Chemical"),
                    ("Synthetic", "Synthetic"),
                    ("Commercial", "Commercial"),
                    ("Plant/Microorganism", "Plant/Microorganism"),
                    ("Other", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
