# Generated by Django 4.2.8 on 2024-12-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0044_alter_chemical_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="check_origin",
            field=models.BooleanField(default=False),
        ),
    ]
