# Generated by Django 4.2.8 on 2024-12-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0046_rename_check_origin_reference_is_plant"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="is_microorganism",
            field=models.BooleanField(default=False),
        ),
    ]
