# Generated by Django 4.2.8 on 2024-12-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0047_reference_is_microorganism"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="np_source",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
