# Generated by Django 4.2.8 on 2024-12-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0048_reference_np_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="is_animal",
            field=models.BooleanField(default=False),
        ),
    ]
