# Generated by Django 4.2.8 on 2024-12-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0049_reference_is_animal"),
    ]

    operations = [
        migrations.AddField(
            model_name="chemical",
            name="label",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
