# Generated by Django 4.2.8 on 2024-12-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0050_chemical_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmittedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
