# Generated by Django 4.2.8 on 2024-12-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0051_submitteddata"),
    ]

    operations = [
        migrations.AddField(
            model_name="submitteddata",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
