# Generated by Django 4.2.8 on 2024-12-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0052_submitteddata_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictionTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=50, unique=True)),
                ("smiles_file", models.FileField(upload_to="smiles_files/")),
                ("results", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
