# Generated by Django 4.2.8 on 2024-12-24 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0053_predictiontask"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="predictiontask",
            name="smiles_file",
        ),
    ]
