# Generated by Django 4.2.8 on 2024-12-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0033_alter_chemical_isnp"),
    ]

    operations = [
        migrations.AddField(
            model_name="chemical",
            name="form",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="chemical",
            name="origin",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Animal", "Animal"),
                    ("Plant", "Plant"),
                    ("Microorganism", "Microorganism"),
                    ("Chemical", "Chemical"),
                    ("Synthetic", "Synthetic"),
                    ("Commercial", "Commercial"),
                    ("Other", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
