# Generated by Django 4.2.8 on 2024-12-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algaecide", "0034_chemical_form_alter_chemical_origin"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Measurement",
        ),
        migrations.AddField(
            model_name="algaespecies",
            name="algaebaselink",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="algaespecies",
            name="empire",
            field=models.CharField(
                blank=True, default="Eukaryota", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="algaespecies",
            name="is_checked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="algaespecies",
            name="kingdom",
            field=models.CharField(
                blank=True, default="Chromista", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="reference",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reference",
            name="toxicity_check",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="algaespecies",
            name="description_source",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="algaespecies",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
